services:
  - type: web
    name: fastapi-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: OPENAI_API_KEY
        value: your-real-api-key
